development:
  dialect: mysql
  database: premutations
  user: user
  password: password
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://user:password@tcp(localhost:3306)/premutations_test?charset=utf8mb4&parseTime=True&loc=Local"}}

production:
  url: {{envOr "DATABASE_URL" "mysql://user:password@tcp(localhost:3306)/premutations?charset=utf8mb4&parseTime=True&loc=Local"}}